### ISSUE TITLE
teamSvc unit test fails a LOT

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#680]
**Describe the bug**
```
Chrome Headless 111.0.5555.0 (Linux x86_64) Service: teamSvc creates an team FAILED
	Expected $.cases[0].caseName = undefined to equal 'Case'.
	    at <Jasmine>
	    at spec/javascripts/angular/services/teamSvc_spec.js:103:26
	    at processQueue (tmp/assets/core-f290278e0c866a8482e67c335b3d5eb3cbfaf0200fe5400e9fce463a6f5c1f01.js:43767:37)
	    at tmp/assets/core-f290278e0c866a8482e67c335b3d5eb3cbfaf0200fe5400e9fce463a6f5c1f01.js:43815:27
	    at Scope.$digest (tmp/assets/core-f290278e0c866a8482e67c335b3d5eb3cbfaf0200fe5400e9fce463a6f5c1f01.js:44934:15
```

**Comment by epugh** [comment]
Not a fix, but I've commented this line out in the tests with a note that it's a "flaky" test....

**Comment by epugh** [comment]
Commented out another test, maybe this is done?

**Comment by epugh** [comment]
I think this is fixed.
