### ISSUE TITLE
Docker-Compose Rails connects to MySQL TOO quickly

### ISSUE THREAD

**Issue by epugh** [o19s/quepid#73]
**Describe the bug**
Sometimes the Rails image tries to connect to MySQL image before it has fully spun up...

**To Reproduce**
1. hard to duplicate, but it happens on `./bin/setup_docker` or on `docker-compose up` with production setup.

**Expected behavior**
Not have this issue!

**Screenshots**

```
Running via Spring preloader in process 20
#<Mysql2::Error::ConnectionError: Can't connect to MySQL server on 'mysql' (111 "Connection refused")>
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8mb4", "collation"=>"utf8mb4_bin", "reconnect"=>false, "pool"=>5, "username"=>"root", "password"=>"password", "host"=>"mysql", "port"=>3306, "database"=>"quepid"}, {:charset=>"utf8mb4", :collation=>"utf8mb4_bin"}
(If you set the charset manually, make sure you have a matching collation)
-- create_table("annotations", {:force=>:cascade})
rake aborted!
Mysql2::Error::ConnectionError: Can't connect to MySQL server on 'mysql' (111 "Connection refused")
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'
/usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `initialize'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/connection_handling.rb:87:in `connection'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:648:in `connection'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:664:in `block in method_missing'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/migration.rb:654:in `method_missing'
/srv/app/db/schema.rb:16:in `block in <top (required)>'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/schema.rb:41:in `instance_eval'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/schema.rb:41:in `define'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/schema.rb:61:in `define'
/srv/app/db/schema.rb:14:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/tasks/database_tasks.rb:221:in `load_schema_for'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/tasks/database_tasks.rb:238:in `block in load_schema_current'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/tasks/database_tasks.rb:278:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/tasks/database_tasks.rb:277:in `each'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/tasks/database_tasks.rb:277:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/tasks/database_tasks.rb:237:in `load_schema_current'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/railties/databases.rake:237:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/activerecord-4.2.11/lib/active_record/railties/databases.rake:241:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

**Additional context**
This is periodically seen, and was reported by a community member "in the wild".

**Comment by Pavithramurthy12** [comment]
As suggested, I just reran the commands, and it worked.
